In [1]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd().resolve()

if not (PROJECT_ROOT / "data" / "raw").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

assert (PROJECT_ROOT / "data" / "raw").exists()

sys.path.insert(0, str(PROJECT_ROOT))

from src.phase2 import standardize_labels_and_splits

print("Project root:", PROJECT_ROOT)

Project root: D:\downloads\project\Diabetic-Retinopathy-Screening-Project

In [2]:
phase2_metadata = standardize_labels_and_splits(
    root=PROJECT_ROOT,
    validation_fraction=0.20,
    random_seed=42,
)

phase2_metadata.head()

,dataset,image_key,image_id,source_split,official_split,image_path,extension,label_dr,has_label,label_source,is_readable,width,height,pil_format,validation_error,label_dr_standard,dr_grade_name,eligible_for_model,model_split,split_reason
0,aptos,aptos__8a58801bb4e89fda,000c1434d8d7,train,NaN,data/raw/aptos/train_images/000c1434d8d7.png,.png,2.0,True,aptos/train.csv,True,3216,2136,PNG,NaN,2,Moderate DR,True,train,stratified_train
1,aptos,aptos__c8827d05711175da,001639a390f0,train,NaN,data/raw/aptos/train_images/001639a390f0.png,.png,4.0,True,aptos/train.csv,True,3216,2136,PNG,NaN,4,Proliferative DR,True,train,stratified_train
2,aptos,aptos__2b8228ecc008b575,0024cdab0c1e,train,NaN,data/raw/aptos/train_images/0024cdab0c1e.png,.png,1.0,True,aptos/train.csv,True,2416,1736,PNG,NaN,1,Mild DR,True,validation,stratified_validation
3,aptos,aptos__f9409e06017fe46c,002c21358ce6,train,NaN,data/raw/aptos/train_images/002c21358ce6.png,.png,0.0,True,aptos/train.csv,True,1050,1050,PNG,NaN,0,No DR,True,train,stratified_train
4,aptos,aptos__11b2efaae2c39263,005b95c28852,train,NaN,data/raw/aptos/train_images/005b95c28852.png,.png,0.0,True,aptos/train.csv,True,2048,1536,PNG,NaN,0,No DR,True,train,stratified_train

In [3]:
pd.read_csv(
    PROJECT_ROOT / "reports/tables/phase2_split_distribution.csv"
)

      dataset model_split  label_dr_standard  images
0       aptos    excluded                NaN    1928
1       aptos       train                0.0    1444
2       aptos       train                1.0     296
3       aptos       train                2.0     799
4       aptos       train                3.0     154
5       aptos       train                4.0     236
6       aptos  validation                0.0     361
7       aptos  validation                1.0      74
8       aptos  validation                2.0     200
9       aptos  validation                3.0      39
10      aptos  validation                4.0      59
11    eyepacs       train                0.0   20648
12    eyepacs       train                1.0    1954
13    eyepacs       train                2.0    4234
14    eyepacs       train                3.0     698
15    eyepacs       train                4.0     566
16    eyepacs  validation                0.0    5162
17    eyepacs  validation                1.0     489
18    eyepacs  validation                2.0    1058
19    eyepacs  validation                3.0     175
20    eyepacs  validation                4.0     142
21      idrid        test                1.0       1
22      idrid        test                2.0      16
23      idrid        test                3.0       6
24      idrid        test                4.0       4
25      idrid       train                1.0       1
26      idrid       train                2.0      18
27      idrid       train                3.0      16
28      idrid       train                4.0      19
29  messidor2       train                0.0     814
30  messidor2       train                1.0     216
31  messidor2       train                2.0     278
32  messidor2       train                3.0      60
33  messidor2       train                4.0      28
34  messidor2  validation                0.0     203
35  messidor2  validation                1.0      54
36  messidor2  validation                2.0      69
37  messidor2  validation                3.0      15
38  messidor2  validation                4.0       7

In [4]:
phase2_metadata.loc[
    phase2_metadata["dataset"] == "idrid",
    ["source_split", "model_split", "split_reason"]
].drop_duplicates()

      source_split model_split          split_reason
40716        train       train  official_idrid_train
40770         test        test   official_idrid_test